version: '3.8'

services:
  frontend:
    container_name: blawdtrack_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # Mapea tu código local al contenedor para la recarga en vivo
      - .:/app
      # Protege los node_modules del contenedor para que no se sobrescriban con los tuyos locales
      - /app/node_modules
    environment:
      # Ayuda a que Vite detecte los cambios de archivos dentro de Docker
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
