import { Box, Typography } from '@mui/material';
import { useCourier } from '../hooks/useCourier';
import { useRegistrationForm } from '../hooks/useRegistrationForm';
import { validateCourierForm } from '../utils/courierFormValidation';
import { TimeWheelField } from '../components/TimeWheelField';
import { WeightWheelField } from '../components/WeightWheelField';
import { composeSchedule } from '../utils/courierSchedule';
import FormField, { FieldShell } from '../components/FormField';
import DocumentFields from '../components/DocumentFields';
import RegistrationFormPage from '../components/RegistrationFormPage';
import { FULL_ROW_SX } from '../components/formStyles';
import { ROUTES } from '../config/routes';

const INITIAL_FORM_DATA = {
  documentType: 'CEDULA',
  documentNumber: '',
  fullName: '',
  phone: '',
  email: '',
  schedule: '',
  scheduleStart: '',
  scheduleEnd: '',
  maxPackageWeightKg: ''
};

// Visual order of the inputs, used to focus the first one with an error.
const FIELD_ORDER = [
  'fullName',
  'phone',
  'email',
  'documentType',
  'documentNumber',
  'schedule',
  'maxPackageWeightKg'
];


// Returns the weight as a number, or null when blank or not numeric.
// Number('') is 0, so a blank value must never be coerced silently;
// null lets the backend validation (@NotNull) report the field.
function parseWeight(rawValue) {
  const trimmed = rawValue.trim();
  if (trimmed === '' || !Number.isFinite(Number(trimmed))) {
    return null;
  }
  return Number(trimmed);
}

// Builds the body expected by POST /api/v1/couriers. The phone is optional
// and omitted when empty; the temporary password is generated by the backend.
function buildCourierPayload(formData) {
  const payload = {
    documentType: formData.documentType,
    documentNumber: formData.documentNumber.trim(),
    fullName: formData.fullName.trim(),
    email: formData.email.trim(),
    schedule: formData.schedule.trim(),
    maxPackageWeightKg: parseWeight(formData.maxPackageWeightKg)
  };
  const phone = formData.phone.trim();
  if (phone) {
    payload.phone = phone;
  }
  return payload;
}

const buildCourierNotice = (outcome) =>
  `Mensajero creado correctamente. Se envió un correo a ${outcome.email} con la contraseña temporal; deberá cambiarla en su primer ingreso.`;

/**
 * Pantalla "Crear mensajero" (HU-003), exclusiva del Super Usuario. Valida el formulario en el cliente
 * (`validateCourierForm`), arma el cuerpo de `POST /api/v1/couriers` y muestra los errores del backend
 * junto a cada campo (`normalizeCourierError`). La contraseña temporal la genera y envía el backend. Al
 * crear el mensajero vuelve al menú de gestión de mensajeros con un aviso de éxito.
 */
export function CourierRegistrationPage() {
  const registration = useCourier();
  const { formData, form, setField, handleSubmit, fieldProps } = useRegistrationForm({
    initialData: INITIAL_FORM_DATA,
    validate: validateCourierForm,
    fieldOrder: FIELD_ORDER,
    discardTo: ROUTES.MODULE_COURIERS,
    registration,
    buildPayload: buildCourierPayload,
    buildNotice: buildCourierNotice
  });
  const { fieldErrors, isSubmitting, globalMessage, severity } = registration;

  // Wheel pickers have no "blur": an inverted range is flagged as soon as both hours are set.
  const setScheduleHour = (name) => (value) =>
    setField(name, value, {
      derive: (next) => ({ ...next, schedule: composeSchedule(next.scheduleStart, next.scheduleEnd) }),
      errorKey: 'schedule',
      validateWhen: (next) => Boolean(next.scheduleStart && next.scheduleEnd)
    });

  return (
    <RegistrationFormPage
      title="Crear mensajero"
      description="Registra a un nuevo mensajero con su horario y la capacidad de carga que puede transportar."
      onSubmit={handleSubmit}
      form={form}
      isSubmitting={isSubmitting}
      submitLabel="Registrar mensajero"
      submittingLabel="Registrando…"
      globalMessage={globalMessage}
      severity={severity}
    >
      <FormField {...fieldProps('fullName')} label="Nombre completo" required placeholder="Ej. Ana Lucía Bermúdez" sx={FULL_ROW_SX} />
      <FormField {...fieldProps('email')} label="Correo electrónico" required type="email" placeholder="nombre@blawdgourmet.com" />
      <FormField {...fieldProps('phone')} label="Teléfono (opcional)" type="tel" placeholder="8888-8888" />
      <DocumentFields field={fieldProps} documentType={formData.documentType} />
      <FieldShell name="maxPackageWeightKg" label="Capacidad máxima de carga (kg)" errorText={fieldErrors.maxPackageWeightKg}>
        <WeightWheelField
          id="maxPackageWeightKg"
          label="Capacidad máxima de carga"
          value={formData.maxPackageWeightKg}
          error={Boolean(fieldErrors.maxPackageWeightKg)}
          onChange={(value) => setField('maxPackageWeightKg', value)}
        />
      </FieldShell>
      <FieldShell name="schedule" label="Horario" errorText={fieldErrors.schedule}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
          <TimeWheelField
            id="schedule"
            label="Hora de entrada"
            value={formData.scheduleStart}
            error={Boolean(fieldErrors.schedule)}
            onChange={setScheduleHour('scheduleStart')}
          />
          <Typography component="span" sx={{ color: 'text.secondary', fontSize: 16 }}>a</Typography>
          <TimeWheelField
            id="scheduleEnd"
            label="Hora de salida"
            value={formData.scheduleEnd}
            error={Boolean(fieldErrors.schedule)}
            onChange={setScheduleHour('scheduleEnd')}
          />
        </Box>
      </FieldShell>
    </RegistrationFormPage>
  );
}

export default CourierRegistrationPage;
