import { useState } from 'react';
import {
  Paper,
  Box,
  Typography,
  TextField,
  MenuItem,
  Button,
  CircularProgress
} from '@mui/material';
import { useCourier } from '../hooks/useCourier';
import { validateCourierForm } from '../utils/courierFormValidation';
import { TimeWheelField } from '../components/TimeWheelField';
import { WeightWheelField } from '../components/WeightWheelField';
import { StatusMessage } from '../components/StatusMessage';

const DOCUMENT_TYPE_OPTIONS = [
  { value: 'CEDULA', label: 'Cédula' },
  { value: 'DIMEX', label: 'DIMEX' },
  { value: 'PASAPORTE', label: 'Pasaporte' }
];

// Example shown in the number field, so the expected format is clear per type.
const DOCUMENT_PLACEHOLDERS = {
  CEDULA: 'Ej. 1-2345-6789',
  DIMEX: 'Ej. 155812345678',
  PASAPORTE: 'Ej. A12345678'
};

// On phones the form uses 2 columns; wide fields span both.
const SPAN_2_SX = { gridColumn: { xs: 'span 2', md: 'auto' } };

const INITIAL_FORM_DATA = {
  documentType: 'CEDULA',
  documentNumber: '',
  fullName: '',
  phone: '',
  email: '',
  schedule: '',
  scheduleStart: '',
  scheduleEnd: '',
  maxPackageWeightKg: ''
};

// Visual order of the inputs, used to focus the first one with an error.
const FIELD_ORDER = [
  'fullName',
  'phone',
  'email',
  'documentType',
  'documentNumber',
  'schedule',
  'maxPackageWeightKg'
];

const LABEL_SX = { fontSize: '0.7rem', fontWeight: 700, letterSpacing: '0.5px', color: '#6B6560', mb: 0.75, display: 'block' };
const INPUT_SX = {
  backgroundColor: '#fff',
  '& .MuiOutlinedInput-root': { borderRadius: '10px', fontSize: '0.9rem', '& fieldset': { borderColor: '#DCD4CA' } },
  '& .MuiOutlinedInput-input': { py: 1.4 }
};

// 24h "HH:MM" -> "6:00 am" (the format the backend already stores).
function formatTime(value) {
  const [h, m] = value.split(':').map(Number);
  const suffix = h >= 12 ? 'pm' : 'am';
  return `${h % 12 || 12}:${String(m).padStart(2, '0')} ${suffix}`;
}

function composeSchedule(start, end) {
  return start && end ? `${formatTime(start)} – ${formatTime(end)}` : '';
}

// Returns the weight as a number, or null when blank or not numeric.
// Number('') is 0, so a blank value must never be coerced silently;
// null lets the backend validation (@NotNull) report the field.
function parseWeight(rawValue) {
  const trimmed = rawValue.trim();
  if (trimmed === '' || !Number.isFinite(Number(trimmed))) {
    return null;
  }
  return Number(trimmed);
}

// Builds the body expected by POST /api/v1/couriers. The phone is optional
// and omitted when empty; the temporary password is generated by the backend.
function buildCourierPayload(formData) {
  const payload = {
    documentType: formData.documentType,
    documentNumber: formData.documentNumber.trim(),
    fullName: formData.fullName.trim(),
    email: formData.email.trim(),
    schedule: formData.schedule.trim(),
    maxPackageWeightKg: parseWeight(formData.maxPackageWeightKg)
  };
  const phone = formData.phone.trim();
  if (phone) {
    payload.phone = phone;
  }
  return payload;
}

export function CourierRegistrationPage() {
  const [formData, setFormData] = useState(INITIAL_FORM_DATA);
  const {
    isSubmitting,
    isSuccess,
    registeredEmail,
    fieldErrors,
    globalMessage,
    severity,
    register,
    setValidationErrors,
    setFieldError,
    clearFieldError
  } = useCourier();

  const handleChange = (event) => {
    const { name, value } = event.target;
    const isSchedule = name === 'scheduleStart' || name === 'scheduleEnd';
    const next = { ...formData, [name]: value };
    if (isSchedule) {
      next.schedule = composeSchedule(next.scheduleStart, next.scheduleEnd);
    }
    setFormData(next);
    clearFieldError(isSchedule ? 'schedule' : name);
    // Wheel pickers have no "blur": flag an inverted range as soon as both hours are set.
    if (isSchedule && next.scheduleStart && next.scheduleEnd) {
      const message = validateCourierForm(next).schedule;
      if (message) setFieldError('schedule', message);
    }
  };

  // Validate a text field when the user leaves it, but only once it has content
  // (an empty required field is reported on submit, not while tabbing through).
  const handleBlur = (event) => {
    const { name, value } = event.target;
    if (!value.trim()) return;
    const message = validateCourierForm(formData)[name];
    if (message) setFieldError(name, message);
  };

  const focusFirstError = (errors) => {
    const firstField = FIELD_ORDER.find((name) => errors[name]);
    // Every input has id === field name, so the DOM lookup is enough.
    if (firstField) document.getElementById(firstField)?.focus();
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (isSubmitting) return;

    const clientErrors = validateCourierForm(formData);
    if (Object.keys(clientErrors).length > 0) {
      setValidationErrors(clientErrors);
      focusFirstError(clientErrors);
      return;
    }

    const outcome = await register(buildCourierPayload(formData));
    if (outcome?.ok) {
      setFormData(INITIAL_FORM_DATA);
    } else if (outcome) {
      focusFirstError(outcome.fieldErrors);
    }
  };

  // Props shared by every input: value, change handler, inline error and
  // accessibility wiring (MUI links helperText through aria-describedby).
  const fieldProps = (name) => ({
    id: name,
    name,
    value: formData[name],
    onChange: handleChange,
    onBlur: handleBlur,
    error: Boolean(fieldErrors[name]),
    helperText: fieldErrors[name] || undefined,
    fullWidth: true,
    sx: INPUT_SX
  });

  const renderField = (name, label, extra, span2 = false) => (
    <Box sx={span2 ? SPAN_2_SX : undefined}>
      <Typography variant="caption" component="label" htmlFor={name} sx={LABEL_SX}>
        {label}
      </Typography>
      <TextField {...fieldProps(name)} {...extra} />
    </Box>
  );

  return (
    <Box sx={{ minHeight: '100vh', backgroundColor: '#FAF8F5', py: { xs: 1.5, sm: 4 }, px: { xs: 1.5, sm: 4 } }}>
      <Paper
        elevation={0}
        sx={{
          maxWidth: 1200,
          mx: 'auto',
          borderRadius: '18px',
          border: '1px solid #E4DED7',
          backgroundColor: '#fff',
          boxShadow: '0 12px 30px rgba(26,60,52,.06)',
          p: { xs: 2, sm: 3.5 },
          textAlign: 'left'
        }}
      >
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: { xs: 1.5, sm: 3 } }}>
          <Box
            sx={{
              width: 34,
              height: 34,
              borderRadius: '9px',
              backgroundColor: '#F1ECE7',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}
          >
            <Box sx={{ width: 16, height: 16, borderRadius: '50%', border: '2.5px solid #1A3C34' }} />
          </Box>
          <Typography component="h1" sx={{ fontSize: '1.06rem', fontWeight: 600, m: 0, color: '#1A3C34' }}>
            Datos del nuevo mensajero
          </Typography>
        </Box>

        <Box component="form" noValidate onSubmit={handleSubmit} sx={{ display: 'flex', flexDirection: 'column', gap: { xs: 1.5, sm: 2.5 } }}>
          {isSuccess && (
            <StatusMessage
              severity="success"
              message={`Mensajero registrado correctamente. Se envió un correo a ${registeredEmail} con la contraseña temporal; deberá cambiarla en su primer ingreso.`}
            />
          )}
          {globalMessage && <StatusMessage severity={severity} message={globalMessage} />}

          <Box
            sx={{
              display: 'grid',
              gap: { xs: '10px 12px', sm: '18px 22px' },
              gridTemplateColumns: { xs: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' },
              alignItems: 'start'
            }}
          >
            {renderField('fullName', 'NOMBRE COMPLETO', { required: true, placeholder: 'Ej. Ana Lucía Bermúdez' }, true)}
            <Box>
              <Typography variant="caption" component="label" htmlFor="documentType" sx={LABEL_SX}>
                TIPO DE DOCUMENTO
              </Typography>
              <TextField {...fieldProps('documentType')} select required>
                {DOCUMENT_TYPE_OPTIONS.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            </Box>
            {renderField('documentNumber', 'NÚMERO DE DOCUMENTO', { required: true, placeholder: DOCUMENT_PLACEHOLDERS[formData.documentType] })}
            {renderField('phone', 'TELÉFONO (OPCIONAL)', { type: 'tel', placeholder: '8888-8888' })}
            {renderField('email', 'CORREO ELECTRÓNICO', { required: true, type: 'email', placeholder: 'nombre@blawdgourmet.com' }, true)}
            <Box>
              <Typography variant="caption" component="label" htmlFor="maxPackageWeightKg" sx={LABEL_SX}>
                CAPACIDAD MÁXIMA DE CARGA (KG)
              </Typography>
              <WeightWheelField
                id="maxPackageWeightKg"
                label="Capacidad máxima de carga"
                value={formData.maxPackageWeightKg}
                error={Boolean(fieldErrors.maxPackageWeightKg)}
                onChange={(v) => handleChange({ target: { name: 'maxPackageWeightKg', value: v } })}
              />
              {fieldErrors.maxPackageWeightKg && (
                <Typography variant="caption" color="error" sx={{ display: 'block', mt: 0.5, mx: 1.75 }}>
                  {fieldErrors.maxPackageWeightKg}
                </Typography>
              )}
            </Box>
            <Box sx={SPAN_2_SX}>
              <Typography variant="caption" component="label" htmlFor="schedule" sx={LABEL_SX}>
                HORARIO
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <TimeWheelField
                  id="schedule"
                  label="Hora de entrada"
                  value={formData.scheduleStart}
                  error={Boolean(fieldErrors.schedule)}
                  onChange={(v) => handleChange({ target: { name: 'scheduleStart', value: v } })}
                />
                <Typography component="span" sx={{ color: '#6B6560' }}>a</Typography>
                <TimeWheelField
                  id="scheduleEnd"
                  label="Hora de salida"
                  value={formData.scheduleEnd}
                  error={Boolean(fieldErrors.schedule)}
                  onChange={(v) => handleChange({ target: { name: 'scheduleEnd', value: v } })}
                />
              </Box>
              {fieldErrors.schedule && (
                <Typography variant="caption" color="error" sx={{ display: 'block', mt: 0.5, mx: 1.75 }}>
                  {fieldErrors.schedule}
                </Typography>
              )}
            </Box>
          </Box>

          <Box sx={{ display: 'flex', gap: 1.5, flexWrap: 'wrap', '& button': { width: { xs: '100%', sm: 'auto' } } }}>
            <Button
              type="submit"
              variant="contained"
              disabled={isSubmitting}
              sx={{
                backgroundColor: '#1A3C34',
                '&:hover': { backgroundColor: '#12322B' },
                textTransform: 'none',
                fontWeight: 600,
                px: 2.75,
                py: { xs: 1.25, sm: 1.5 },
                borderRadius: '10px',
                gap: 1.2,
                boxShadow: 'none'
              }}
            >
              {isSubmitting ? (
                <>
                  <CircularProgress size={18} color="inherit" />
                  Registrando…
                </>
              ) : (
                <>
                  Registrar mensajero
                  <Box component="span" sx={{ width: 12, height: 12, borderRadius: '50%', backgroundColor: '#FF6C0E' }} />
                </>
              )}
            </Button>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
}

export default CourierRegistrationPage;
