import { useState } from 'react';
import {
  Container,
  Paper,
  Box,
  Typography,
  TextField,
  MenuItem,
  Button,
  CircularProgress
} from '@mui/material';
import { useCourier } from '../hooks/useCourier';
import { validateCourierForm } from '../utils/courierFormValidation';
import { StatusMessage } from '../components/StatusMessage';

// 1. Importamos la imagen desde la carpeta assets
import logo from '../assets/Logo.png';

function BlawdTrackLogo() {
  return (
    <Box
      sx={{
        width: 46,
        height: 46,
        backgroundColor: '#ffffff',
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0px 2px 4px rgba(0,0,0,0.1)'
      }}
    >
      {/* 2. Reemplazamos el SVG por la etiqueta img llamando a la variable 'logo' */}
      <img
        src={logo}
        alt="BlawdTrack Logo"
        style={{ width: '34px', height: '34px', objectFit: 'contain' }}
      />
    </Box>
  );
}

function PersonHeaderIcon() {
  return (
    <svg width="26" height="26" viewBox="0 0 24 24" fill="#ffffff">
      <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
    </svg>
  );
}

const DOCUMENT_TYPE_OPTIONS = [
  { value: 'CEDULA', label: 'Cédula' },
  { value: 'DIMEX', label: 'DIMEX' },
  { value: 'PASAPORTE', label: 'Pasaporte' }
];

const INITIAL_FORM_DATA = {
  documentType: 'CEDULA',
  documentNumber: '',
  fullName: '',
  phone: '',
  email: '',
  schedule: '',
  maxPackageWeightKg: ''
};

// Visual order of the inputs, used to focus the first one with an error.
const FIELD_ORDER = [
  'fullName',
  'phone',
  'email',
  'documentType',
  'documentNumber',
  'schedule',
  'maxPackageWeightKg'
];

const LABEL_SX = { fontWeight: 'bold', color: '#4a4a4a', mb: 0.8, display: 'block' };
const INPUT_SX = { backgroundColor: '#ffffff', borderRadius: 2 };
const ROW_SX = { display: 'flex', gap: 2.5, flexDirection: { xs: 'column', sm: 'row' } };

// Returns the weight as a number, or null when blank or not numeric.
// Number('') is 0, so a blank value must never be coerced silently;
// null lets the backend validation (@NotNull) report the field.
function parseWeight(rawValue) {
  const trimmed = rawValue.trim();
  if (trimmed === '' || !Number.isFinite(Number(trimmed))) {
    return null;
  }
  return Number(trimmed);
}

// Builds the body expected by POST /api/v1/couriers. The phone is optional
// and omitted when empty; the temporary password is generated by the backend.
function buildCourierPayload(formData) {
  const payload = {
    documentType: formData.documentType,
    documentNumber: formData.documentNumber.trim(),
    fullName: formData.fullName.trim(),
    email: formData.email.trim(),
    schedule: formData.schedule.trim(),
    maxPackageWeightKg: parseWeight(formData.maxPackageWeightKg)
  };
  const phone = formData.phone.trim();
  if (phone) {
    payload.phone = phone;
  }
  return payload;
}

export function CourierRegistrationPage() {
  const [formData, setFormData] = useState(INITIAL_FORM_DATA);
  const {
    isSubmitting,
    isSuccess,
    registeredEmail,
    fieldErrors,
    globalMessage,
    severity,
    register,
    setValidationErrors,
    clearFieldError
  } = useCourier();

  const handleChange = (event) => {
    const { name, value } = event.target;
    setFormData((previousData) => ({
      ...previousData,
      [name]: value
    }));
    clearFieldError(name);
  };

  const focusFirstError = (errors) => {
    const firstField = FIELD_ORDER.find((name) => errors[name]);
    // Every input has id === field name, so the DOM lookup is enough.
    if (firstField) document.getElementById(firstField)?.focus();
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (isSubmitting) return;

    const clientErrors = validateCourierForm(formData);
    if (Object.keys(clientErrors).length > 0) {
      setValidationErrors(clientErrors);
      focusFirstError(clientErrors);
      return;
    }

    const outcome = await register(buildCourierPayload(formData));
    if (outcome?.ok) {
      setFormData(INITIAL_FORM_DATA);
    } else if (outcome) {
      focusFirstError(outcome.fieldErrors);
    }
  };

  // Props shared by every input: value, change handler, inline error and
  // accessibility wiring (MUI links helperText through aria-describedby).
  const fieldProps = (name) => ({
    id: name,
    name,
    value: formData[name],
    onChange: handleChange,
    error: Boolean(fieldErrors[name]),
    helperText: fieldErrors[name] || undefined,
    fullWidth: true,
    sx: INPUT_SX
  });

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Paper
        elevation={2}
        sx={{
          borderRadius: 4,
          overflow: 'hidden',
          backgroundColor: '#eae7e1'
        }}
      >
        <Box sx={{ height: '5px', backgroundColor: '#ff6b00', width: '100%' }} />

        <Box
          sx={{
            backgroundColor: '#183a2e',
            color: '#ffffff',
            py: 3.5,
            px: 2,
            textAlign: 'center',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center'
          }}
        >
          <BlawdTrackLogo />
          <Typography
            variant="subtitle1"
            fontWeight="bold"
            sx={{ color: '#ffffff', mt: 1, letterSpacing: '0.5px', fontSize: '1.05rem' }}
          >
            BlawdTrack
          </Typography>

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1.5 }}>
            <PersonHeaderIcon />
            <Typography variant="h5" component="h1" fontWeight="bold">
              Registro de mensajero
            </Typography>
          </Box>

          <Typography variant="body2" sx={{ opacity: 0.85, mt: 0.5, fontSize: '0.9rem' }}>
            Completa los datos para dar de alta a un nuevo mensajero.
          </Typography>
        </Box>

        <Box
          component="form"
          noValidate
          onSubmit={handleSubmit}
          sx={{
            p: { xs: 2.5, sm: 4 },
            display: 'flex',
            flexDirection: 'column',
            gap: 2.5
          }}
        >
          {isSuccess && (
            <StatusMessage
              severity="success"
              message={`Mensajero registrado correctamente. Se envió un correo a ${registeredEmail} con la contraseña temporal; deberá cambiarla en su primer ingreso.`}
            />
          )}
          {globalMessage && <StatusMessage severity={severity} message={globalMessage} />}

          <Box sx={ROW_SX}>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="fullName" sx={LABEL_SX}>
                NOMBRE COMPLETO
              </Typography>
              <TextField {...fieldProps('fullName')} required placeholder="Ej. María José Solano" />
            </Box>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="phone" sx={LABEL_SX}>
                TELÉFONO (OPCIONAL)
              </Typography>
              <TextField {...fieldProps('phone')} type="tel" placeholder="8888-8888" />
            </Box>
          </Box>

          <Box sx={ROW_SX}>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="email" sx={LABEL_SX}>
                CORREO ELECTRÓNICO
              </Typography>
              <TextField
                {...fieldProps('email')}
                required
                type="email"
                placeholder="nombre@blawdgourmet.com"
              />
            </Box>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="documentType" sx={LABEL_SX}>
                TIPO DE DOCUMENTO
              </Typography>
              <TextField {...fieldProps('documentType')} select required>
                {DOCUMENT_TYPE_OPTIONS.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            </Box>
          </Box>

          <Box sx={ROW_SX}>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="documentNumber" sx={LABEL_SX}>
                NÚMERO DE DOCUMENTO
              </Typography>
              <TextField {...fieldProps('documentNumber')} required placeholder="1-2345-6789" />
            </Box>
            <Box sx={{ flex: 1 }}>
              <Typography variant="caption" component="label" htmlFor="schedule" sx={LABEL_SX}>
                HORARIO
              </Typography>
              <TextField {...fieldProps('schedule')} required placeholder="Ej. 6:00 am – 2:00 pm" />
            </Box>
          </Box>

          <Box sx={{ width: { xs: '100%', sm: '48.5%' } }}>
            <Typography variant="caption" component="label" htmlFor="maxPackageWeightKg" sx={LABEL_SX}>
              CAPACIDAD MÁXIMA DE CARGA (KG)
            </Typography>
            <TextField
              {...fieldProps('maxPackageWeightKg')}
              required
              type="number"
              placeholder="Ej. 25"
              slotProps={{ htmlInput: { min: 0, step: 0.01 } }}
            />
          </Box>

          <Button
            type="submit"
            fullWidth
            variant="contained"
            size="large"
            disabled={isSubmitting}
            sx={{
              mt: 2,
              py: 1.8,
              fontWeight: 'bold',
              backgroundColor: '#183a2e',
              '&:hover': {
                backgroundColor: '#10271e'
              },
              textTransform: 'none',
              fontSize: '1rem',
              borderRadius: 2.5,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 1.2
            }}
          >
            {isSubmitting ? (
              <>
                <CircularProgress size={20} color="inherit" />
                Registrando…
              </>
            ) : (
              <>
                Registrar mensajero
                <Box
                  component="span"
                  sx={{
                    width: 12,
                    height: 12,
                    borderRadius: '50%',
                    backgroundColor: '#ff6b00',
                    display: 'inline-block'
                  }}
                />
              </>
            )}
          </Button>
        </Box>
      </Paper>
    </Container>
  );
}

export default CourierRegistrationPage;
